nolic

diff --git a/.github/workflows/build-android-apk.yml b/.github/workflows/build-android-apk.yml
--- a/.github/workflows/build-android-apk.yml
+++ b/.github/workflows/build-android-apk.yml
@@ -18,28 +18,28 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
 
-      - name: Check Unity License File
-        run: |
-          if [[ -z "${UNITY_LICENSE_XML_B64:-}" ]]; then
-            echo "::error::UNITY_LICENSE_XML_B64 is missing/empty"
-            exit 1
-          fi
+      # - name: Check Unity License File
+      #   run: |
+      #     if [[ -z "${UNITY_LICENSE_XML_B64:-}" ]]; then
+      #       echo "::error::UNITY_LICENSE_XML_B64 is missing/empty"
+      #       exit 1
+      #     fi
 
-          echo "UNITY_LICENSE_XML_B64 is set (len=${#UNITY_LICENSE_XML_B64})"
-          mkdir -p ~/.config/unity3d/Unity/licenses
-          printf '%s' "$UNITY_LICENSE_XML_B64" | base64 -d > ~/.config/unity3d/Unity/licenses/UnityEntitlementLicense.xml
-          # mkdir -p artifacts/unity-license
-          # cp ~/.config/unity3d/Unity/licenses/UnityEntitlementLicense.xml artifacts/unity-license/UnityEntitlementLicense.xml            
-          # printf '%s' "$UNITY_LICENSE_XML_B64" > ~/.config/unity3d/Unity/licenses/UnityEntitlementLicense.xml.b64
-          sudo apt-get update
-          sudo apt-get install -y libxml2-utils
-          if xmllint --noout ~/.config/unity3d/Unity/licenses/UnityEntitlementLicense.xml; then
-            echo "XML is valid"
-          else
-            echo "Invalid XML file. Please check the license file stored."
+      #     echo "UNITY_LICENSE_XML_B64 is set (len=${#UNITY_LICENSE_XML_B64})"
+      #     mkdir -p ~/.config/unity3d/Unity/licenses
+      #     printf '%s' "$UNITY_LICENSE_XML_B64" | base64 -d > ~/.config/unity3d/Unity/licenses/UnityEntitlementLicense.xml
+      #     # mkdir -p artifacts/unity-license
+      #     # cp ~/.config/unity3d/Unity/licenses/UnityEntitlementLicense.xml artifacts/unity-license/UnityEntitlementLicense.xml            
+      #     # printf '%s' "$UNITY_LICENSE_XML_B64" > ~/.config/unity3d/Unity/licenses/UnityEntitlementLicense.xml.b64
+      #     sudo apt-get update
+      #     sudo apt-get install -y libxml2-utils
+      #     if xmllint --noout ~/.config/unity3d/Unity/licenses/UnityEntitlementLicense.xml; then
+      #       echo "XML is valid"
+      #     else
+      #       echo "Invalid XML file. Please check the license file stored."
             
-            exit 1
-          fi
+      #       exit 1
+      #     fi
         
 
       - name: Install build dependencies
@@ -69,12 +69,12 @@ jobs:
           echo "$(dirname "$UNITY_BIN")" >> "$GITHUB_PATH"
 
       - name: Run build pipeline (tee log)
-        env:
-          UNITY_LICENSE_XML_B64: ${{ secrets.UNITY_LICENSE_XML_B64 }}
+        # env:
+        #   UNITY_LICENSE_XML_B64: ${{ secrets.UNITY_LICENSE_XML_B64 }}
         run: |
           set -euo pipefail
-          mkdir -p ~/.config/unity3d/Unity/licenses
-          printf '%s' "$UNITY_LICENSE_XML_B64" | base64 -d > ~/.config/unity3d/Unity/licenses/UnityEntitlementLicense.xml       
+          # mkdir -p ~/.config/unity3d/Unity/licenses
+          # printf '%s' "$UNITY_LICENSE_XML_B64" | base64 -d > ~/.config/unity3d/Unity/licenses/UnityEntitlementLicense.xml       
           mkdir -p artifacts/unity-logs
           ./unity/first/build_android.sh 2>&1 | tee artifacts/unity-logs/build.log
 
