xmlint

diff --git a/.github/workflows/build-android-apk.yml b/.github/workflows/build-android-apk.yml
--- a/.github/workflows/build-android-apk.yml
+++ b/.github/workflows/build-android-apk.yml
@@ -19,7 +19,13 @@ jobs:
         run: |
           mkdir -p ~/.config/unity3d/Unity/licenses
           echo "${{ secrets.UNITY_LICENSE_XML }}" > ~/.config/unity3d/Unity/licenses/UnityEntitlementLicense.xml
-
+          sudo apt-get install -y xmlstarlet
+          if xmllint --noout ~/.config/unity3d/Unity/licenses/UnityEntitlementLicense.xml; then
+            echo "XML is valid"
+          else
+            echo "Invalid XML file. Please check the license file."
+            exit 1
+          fi
 
       - name: Install build dependencies
         run: sudo ./unity/first/install_build_dependencies.sh
